version: '3'
services:
  postgres:
    image: postgres:12
    env_file: .pgconfig
    volumes:
      - /srv/docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    env_file: .pgconfig
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres